### ISSUE TITLE
如何删除模型 标 的点？ctrl+z只能撤销操作，没法对之前的点进行处理。

### ISSUE THREAD

**Issue by codemaster17611** [Elin24/cclabeler#15]
大佬好，我是基于自己训练的模型能给数据集标一部分点，但是有些点是错误的，如何删除？
其次，网页中 labelme.html中line74 <canvas id="cvs" width="1440" height="1000"> 与上面的功能界面，另起了一行显示，能否咨询下 是电脑分辨率问题吗？

**Comment by Elin24** [comment]
1. 左侧又有个rectify的按钮，点击以后，点击对应的point或者box，按键盘上的 `del` 就可以删除

**Comment by codemaster17611** [comment]
谢谢
